# Generated by Django 5.2 on 2026-06-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndexDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(db_index=True, max_length=20)),
                ('base_date', models.DateField(db_index=True)),
                ('close_price', models.FloatField()),
                ('change', models.FloatField()),
                ('change_rate', models.FloatField()),
            ],
            options={
                'ordering': ['-base_date'],
                'constraints': [models.UniqueConstraint(fields=('index_name', 'base_date'), name='uniq_index_date')],
            },
        ),
    ]
