# Generated by Django 5.1.15 on 2026-06-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_marketindexdaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymarketweather',
            name='weather_status',
            field=models.CharField(choices=[('VERY_SUNNY', '매우맑음'), ('SUNNY', '맑음'), ('CLOUDY', '흐림'), ('RAINY', '비'), ('STORMY', '돌풍')], default='SUNNY', max_length=20),
        ),
    ]
