# Generated by Django 5.2 on 2026-06-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_dailymarketweather_weather_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymarketweather',
            name='weather_status',
            field=models.CharField(choices=[('VERY_SUNNY', '매우맑음'), ('SUNNY', '맑음'), ('CLOUDY', '흐림'), ('RAINY', '비'), ('STORMY', '비+천둥')], default='SUNNY', max_length=20),
        ),
    ]
