# Generated by Django 5.2.15 on 2026-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_dailymarketweather_weather_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(default=0),
        ),
    ]
