# Generated by Django 5.2.15 on 2026-06-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investment_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='주식 성향'),
        ),
    ]
