# Generated by Django 5.2 on 2026-06-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('stocks', '0002_marketindexdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_stocks', to='news.sector')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_links', to='stocks.stock')),
            ],
            options={
                'ordering': ['sector', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('sector', 'stock'), name='uniq_sector_stock')],
            },
        ),
    ]
