# Generated by Django 5.2 on 2026-06-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_purge_legacy_sector_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment',
            field=models.CharField(choices=[('긍정', '긍정'), ('부정', '부정'), ('미분석', '미분석')], db_index=True, default='미분석', max_length=10),
        ),
    ]
